### ISSUE TITLE
Feature Request: Save last used settings when adding a run

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#1]
Hi,

I think many people will do multiple abyssal runs for the same filament type and with the same ship.
So I think it would be very helpful if the "Add run" page could save the last used settings for at least the top section (type, tier and ship).

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

Great idea! I'll update this issue when it's done. 

BR

**Comment by molbal** [comment]
Hello,

The site was just updated with the feature.

Thanks for the suggestion,

Regards
