### ISSUE TITLE
Cannot delete fitting

### ISSUE THREAD

**Issue by snoberg** [molbal/abyss-tracker#100]
I am unable to delete https://abyss.eve-nt.uk/fit/4209

When I try it just takes me to a "something went wrong" page

This is a depreciated fit that I have a current version for and would like for it to be gone.

**Comment by molbal** [comment]
Oh no this again

**Comment by molbal** [comment]
![kép](https://user-images.githubusercontent.com/5754480/120936080-4b2e7880-c706-11eb-8918-869d311461b6.png)

**Comment by snoberg** [comment]
Haha, has this happened before I take it? I set it to private just to get it off the search results.

**Comment by molbal** [comment]
Yeah two times already! Both times a DB rollback was caused by foreign keys so this is what I suspect again

**Comment by Nostuh** [comment]
This I believe has been fixed.   Tested with a user on a couple of them.  Let me know!
