### ISSUE TITLE
Find fit by id when adding a new run

### ISSUE THREAD

**Issue by RSBat** [molbal/abyss-tracker#102]
There are some fits with the same name like several "T4 Gamma" Gila fits. There is no way to know which one you select when adding a run.
I suggest adding an option to search by fit id e.g. typing 4785 would find this fit: https://abyss.eve-nt.uk/fit/4785

**Comment by molbal** [comment]
You are right it was missing - its there now, thanks for the ticket:
![kép](https://user-images.githubusercontent.com/5754480/128610428-897d8f9e-557f-4b1e-93a0-7e4cb3f0d64d.png)
