### ISSUE TITLE
Icons for tier and type are switched in search results

### ISSUE THREAD

**Issue by TeaDrivenDev** [molbal/abyss-tracker#105]
**Describe the bug**
The icons for tier and type in search results are switched.

**To Reproduce**
1. Go to "Search"
2. Run any valid search
-> The "Tier" shows the number for the tier, but the icon for the type; the "Type" shows the name for the type, but the icon for the tier.

**Expected behavior**
The "Tier" column shows the number and icon for the tier; the "Type" column shows the name and icon for the type.

**Screenshots**
![image](https://user-images.githubusercontent.com/2247219/126415232-5fc1f7d2-90c2-4ace-ae29-5f708d1b94ba.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 89.0.2

**Smartphone:**
 - Device: Samsung Galaxy S20
 - OS: Android 11
 - Browser: Firefox
 - Version: 90.1.1

**Comment by molbal** [comment]
Nice catch, thank you, especially for the thorough report - fixed and pushed to prod.
