### ISSUE TITLE
500 error when viewing ship fitting

### ISSUE THREAD

**Issue by bjarnis** [molbal/abyss-tracker#106]
**Describe the bug**
500 error when viewing ship fitting

**To Reproduce**
1. Open any ship fit, f.e. https://abyss.eve-nt.uk/fit/5530

**Expected behavior**
Show selected ship fitting.

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser vivaldi
 - Version 4.1.2369.15

**Additional context**
Error 500

This is an 'Internal Server Error' - this is sometimes caused by EVE downtime (check here) or its simply caused by a bug in the Abyss Tracker.

**Comment by ZaxLofful** [comment]
This is also happening to me, no matter what ship fit I go and look at.

**Comment by molbal** [comment]
Thanks for the report, its fixed. It was caused by a combination of performance issues resulting in timeouts, ESI errors, and a new api token authentication method affecting guest users.
