### ISSUE TITLE
Chromium-based resource load failure

### ISSUE THREAD

**Issue by Parisito1234** [molbal/abyss-tracker#107]
**Describe the bug**
Chromiuim-Based browsers do not load all assets outside of root page.
Browser console is reporting Mixed Content HTTP insecure requests from `http://127.0.0.1:8000/...` - not sure why localhost is being called.

**To Reproduce**
- Open any webpage on a chromium-based browser
- Only able to see simple HTML DOM instead of HTML with CSS or external assets.

**Expected behavior**
Webpage should load with full set of icons, images, and CSS.

**Screenshots**
![image](https://user-images.githubusercontent.com/58274947/128720970-412cf115-59d3-4347-8053-6d97452419ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 92.0.4515.131 & Edge 92.0.902.67

**Additional context**
First time ever trying to load page, apologies if missing setup steps.

**Comment by molbal** [comment]
Huh its because I accidentally pushed a bunch of dev config files to production.

**Comment by molbal** [comment]
Restored from backup, site back up.

A redis restart was also needed.
