### ISSUE TITLE
StartWatcher is not working

### ISSUE THREAD

**Issue by Ceraci** [molbal/abyss-tracker#11]
The first time you use Stop Startwatcher it is necessary to log in to SSO and make the permissions, if in case you remove it from the managment panel directly in the EVE Managment services when relogging in the Abyss Tracker system and activating the Stop Startwatcher it does not return to relog via SSO and allow it to be used. How do I get the timer to reactivate with the permissions to use it automatically instead of having to do it manually every time?

**Comment by molbal** [comment]
Now this is a case I forgot to think about when I made it. If you send me a DM in-game I'll know which user to reset manually. 

Then after the ship fits release I'll make an every in settings to handle it.

Cheers

**Comment by Ceraci** [comment]
> Now this is a case I forgot to think about when I made it. If you send me a DM in-game I'll know which user to reset manually.
> 
> Then after the ship fits release I'll make an option in settings to handle it.
> 
> Cheers

Hello ... my public profile is https://abyss.eve-nt.uk/char/187619130 and my pilot ingame name is Ceraci ... however I did not understand what would be "DM" requested in-game.

Thank you in advance for your help and congratulations on the extraordinary tool that helps us a lot.

**Comment by molbal** [comment]
It's good like this, I thought you wanted to keep your identity out of the issue.. but your name is the same so never mind that :) 

I meant a Direct Message as DM.

Your very welcome, I'll try to unlock your stopwatch today

**Comment by molbal** [comment]
Hello,

You can authenticate again and then the stopwatch should work again.

I'm keeping this ticket open until I do a normal solution though.

**Comment by Ceraci** [comment]
> Hello,
> 
> You can authenticate again and then the stopwatch should work again.
> 
> I'm keeping this ticket open until I do a normal solution though.


Hello ... great job ... I managed to use the automatic timer again ... thank you

**Comment by molbal** [comment]
Glad it worked. 

If it happens again you can now reset it yourself from the settings.
(From version 1.4.2: https://github.com/molbal/abyss-tracker/releases/tag/1.4.2)
