### ISSUE TITLE
Badge for Hull Size Defaults to "CRUISER SIZE SHIPS" on Runs Search Results Page

### ISSUE THREAD

**Issue by Aalve** [molbal/abyss-tracker#112]
**Describe the bug**
Badge for hull size criteria on search results page ("search/execute" route) defaults to "Cruiser" no matter what is picked, however the condition for the query is what is selected, so the results still match.

**To Reproduce**
1. Go to "Runs" page: https://abyss.eve-nt.uk/search 
2. Choose a "Hull Size" that is not "Cruiser size"
3. Press "Search"
4. On resulting page load, look at the top under "Displaying" and the badge should incorrectly read "CRUISER SIZE SHIPS"

**Expected behavior**
On step 4 of the reproduction steps, the badge should show the appropriate hull size you chose on the previous page from step 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/8605973/144943132-e39522c8-2f38-442e-ab8d-c6e9bf128c17.png)

![image](https://user-images.githubusercontent.com/8605973/144943149-2959400e-ad99-4dea-ab54-d03913490043.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome

**Additional context**
I believe the issue is this line:
https://github.com/molbal/abyss-tracker/blob/146891da9106b34595fee517283f59b2e7251c81/app/Http/Controllers/SearchController.php#L83

The encapsulating if statement already checks if the field was filled, so the condition for this ternary operator will always resolve to true and choose "Cruiser" for this SearchCriteria's name. However, the actual selected value is set as its value, so we end up seeing frigate results with the "CRUISER SIZE SHIPS" badge.

**Comment by molbal** [comment]
Excellent catch - thank you for taking the time to pinpoint the root cause as well

**Comment by molbal** [comment]
Scheduled for release 1.11 (but already patched)
