### ISSUE TITLE
Uptime 404

### ISSUE THREAD

**Issue by Doyley3731** [molbal/abyss-tracker#113]
In the footer of each page the link to the uptime monitor ( https://uptime.abyss.eve-nt.uk/ ) 404s

**Comment by molbal** [comment]
Thanks - the provider discontinued its custom url support in their free plan - the status page is now https://stats.uptimerobot.com/nZ3W3TGrZG

**Comment by molbal** [comment]
Scheduled for release 1.11 (but already patched)
