### ISSUE TITLE
Several uploaded fits will not finish calculating

### ISSUE THREAD

**Issue by VexorJockey** [molbal/abyss-tracker#117]
I've uploaded 3 fits so far and none of them will finish calculating.
I upload the fit in the editor, change the name in the editor, and make a bulleted list of instructions in the description.
I swap the status to works and do a run for the fit. Days have passed and still none have finished calculating.
I've tried cycling the works status, removing the bulleted list, changing the fit from public to private. 
I've completely deleted fits and reuploaded them no change.

**Comment by molbal** [comment]
It was a server issue:
![image](https://user-images.githubusercontent.com/5754480/156926452-73d32849-db06-45d3-8057-6277c0d64e8f.png)

It's restored now and the site is processing the queued fits
