### ISSUE TITLE
Auto-before cargo

### ISSUE THREAD

**Issue by s0rInb** [molbal/abyss-tracker#12]
Hello, thank you for this project. It's awesome!

It will be really helpful if "before cargo" can load from previous "after cargo". Some manual checkbox maybe?

**Comment by molbal** [comment]
Hey,

Excellent idea! I'm working on the ship fits function, I'll add this feature to the release coming after it

Cheers

**Comment by molbal** [comment]
Hello,

It is now done. If the next run starts within 60 minutes of finishing the previous one, the website will load the old run's "After cargo" box to the "Before cargo" box of the new run.

(From version 1.4.2: https://github.com/molbal/abyss-tracker/releases/tag/1.4.2)

Thanks,
Veetor
