### ISSUE TITLE
Small Typo on the ship-lost-icon tooltip in all runs

### ISSUE THREAD

**Issue by CrenshawCoding** [molbal/abyss-tracker#16]
https://i.imgur.com/9RrKz1p.png

It says "railed" instead of "failed" on the ship-lost-icon tooltip in all runs

**Comment by molbal** [comment]
Hey,

Thanks, I haven't noticed it yet. I'll fix it next patch.

**Comment by molbal** [comment]
Its fixed with v1.5

**Comment by zmsMarc** [comment]
Typo is still in 4 more places:
![grafik](https://user-images.githubusercontent.com/9104198/96477605-00272a00-1237-11eb-97a0-e993aae5a2f1.png)

**Comment by molbal** [comment]
Thanks Marc - I'll weed these out in the 1.8 branch!

**Comment by molbal** [comment]
Damn. I forgot.

**Comment by molbal** [comment]
Fixed, now :)
