### ISSUE TITLE
Cannot add a fit

### ISSUE THREAD

**Issue by CrenshawCoding** [molbal/abyss-tracker#18]
Was just trying to add a fit for the first time, got this after hitting save:

<details>
<summary>Image</summary>
<img src="https://i.imgur.com/3GknwjL.png">
</details>

My inputs:

Fit:
> [Ikitursa, *yayo]
> Energized Adaptive Nano Membrane II
> Medium Armor Repairer II
> Reactive Armor Hardener
> Medium Ancillary Armor Repairer
> Entropic Radiation Sink II
> Entropic Radiation Sink II
> 
> Caldari Navy Stasis Webifier
> Thukker Large Cap Battery
> 50MN Quad LiF Restrained Microwarpdrive
> Republic Fleet Medium Cap Battery
> 
> Veles Heavy Entropic Disintegrator
> Small Energy Nosferatu II
> 
> Medium Auxiliary Nano Pump II
> Medium Auxiliary Nano Pump II
> 
> 
> 
> Federation Navy Hammerhead x7
> 
> Occult M x2043
> Mystic M x1778
> Nanite Repair Paste x216
> Standard Exile Booster x1
> Agency 'Pyrolancea' DB5 Dose II x1

Description:

> Pretty chill fit. Zoom around sniping the Extraction nodes with Mystic, fly to gate and just sit there kiling stuff with Occult while your mtu gets you the money.
> 
> I use 
> RS-603
> MR-703
> RL-1003
> 
> with it

**Comment by Salvoxia** [comment]
I encountered this as well, but only when I pasted my description into the field. A workround seems to be actually typing some characters into that field, then deleting them again.
Only pasting seems to let the editor think the window is still empty.

**Comment by CrenshawCoding** [comment]
Thanks for the workaround, deleting the last character and typing it again worked after I pasted it.

**Comment by molbal** [comment]
Huh I haven't notie

**Comment by molbal** [comment]
Hi,

I made the description field optional - it was a mistake to make it mandatory in the first place.

Best regards,
Veetor
