### ISSUE TITLE
Enhancement: Force user to select at least one weather/tier recommendation for fits

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#19]
Hi,

I played around with the fitting management and accidentally added a fit that was not recommended for any type of weather or tier. If that is not by design (as in "I completed Abyssals with a fit that is not actually recommended it for") I suggest to force the user to select at least one recommendation.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

Good idea. Indeed there is nothing enforcing this right now

I'll keep this issue open until a new validation rule is set

Best regards,
Veetor

**Comment by molbal** [comment]
Hi,

Done, but the validation is only server-side.

Best regards
Veetor
