### ISSUE TITLE
Enhancement: Edit fits

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#20]
Hi,

I'm pretty sure that one is already on your own internal list, but just to make sure:
For the future I suggest the possibility to edit fits (maybe with versioning, if that's a concern).
I just needed three attempts to get my first fitting right, and since there's no preview function and edit functions, I had to delete it two times. ;-)

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

Yeah we only have deletion right now. I will have a revision system ready, because other people can link their fits to them. So it's a bit bigger task but definitely in my todo list

Best regards,
Veetor

**Comment by molbal** [comment]
Scheduled for next patch: 1.8

**Comment by molbal** [comment]
Published with 1.8. I haven't heard from you a while, I hope you are fine

**Comment by Salvoxia** [comment]
Thank you for continuing your development effort!
I have to admit I'm on kind of an EVE break, so yeah, haven't been to the Abyss lately. But I will be back, I'm sure.
I do leave likes on Patreon, following you there :)

**Comment by molbal** [comment]
Enjoy your break, I'm glad you are okay :)
