### ISSUE TITLE
Enhancement: Permalinks for search results

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#21]
Hi,

right now it's not possible to perform a search and share the result of the search with that exact search criteria.
I suggest some kind of perma-link functionality to be able to share search results. Either directly code the search criteria into the URL of the search result (browsing to that URL would search again using the same critera), or encode that specific result into some kind of hash and cache that exact search result for a limited time (couple of days?).

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

There is an "open results in a new tab" button that is kind of for this, but generates a long and messy URL. Of course it would be better with tokens but for now it's kind of low prio because it would add very little functionality unless I misunderstood it

Best regards
Veetor

**Comment by Salvoxia** [comment]
Actually I meant the [Advanced Search](https://abyss.eve-nt.uk/search) that has that problem.
But I guess the same system for sharing results could be used for both, whatever that might eventually be.

**Comment by molbal** [comment]
I see now! Behind the scenes, both search functions take both GET and POST params, that's how I link filaments for example https://abyss.eve-nt.uk/search/execute?type=Firestorm and ships https://abyss.eve-nt.uk/fits/search?SHIP_ID=17715 - but I get it now

**Comment by Salvoxia** [comment]
Oh, one more thing I noticed: The search results seem to be limited to 250 results. Is that by design?

**Comment by molbal** [comment]
Yes, that's primarily to prevent someone using tricky search filters to get all data. Im not worried of someone getting opsec info, but I think it wouldn't be good for site performance. + I don't see any reason where someone would need all the data from the page as I would just make them and endpoint or do an anonymized data export

**Comment by Salvoxia** [comment]
Okay, I understand the reasoning behind that.
However, the way the search works now, always the oldest 250 results are displayed. So sooner or later that will become static data for all possible combinations of search filters (as long as none of the really old runs are deleted).
I suggest to return the newest 250 results instead.

**Comment by molbal** [comment]
This is valid! I'll add ordeding in the next update

**Comment by molbal** [comment]
Online as of 1.7
