### ISSUE TITLE
Problems finding a fit when adding a run

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#22]
Hi,

I added an anonym fit and then tried to add a run and select that fitting. My ship hull was pre-selected from my previous run. At first, it was displayed under "My ... fits" in the search dropdown menu. 
For the second and third run it was no longer shown ("You don't have any ... fits"), but I was able to find it by search for its ID.
After the fourth run, I cannot find at by any means. Not by searching for the ID, the full name or any words the name contains.
Unfortunately, I don't know how to consistently reproduce it.

If you need more information, I'll try to provide it
Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

The fit finder is unreasonably complicated. I am sure it's not user error, so I'll look up how to reliably reproduce it - after that I will know a fix will be possible

Best regards
Veetor

**Comment by molbal** [comment]
Fixed with commit cf3b6aab33acdd6de4d02a9685e57e425cc88bb2
