### ISSUE TITLE
(Re-)remember run privacy setting and last selected fit for specific run

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#23]
Hi,

after the update to the privacy setting on the "Add run" page, it no longer remembers the last selected setting.
Also, it doesn't remember the last selected fitting for that specific hull. Would be cool, if that could be pre-selected when adding a run, or when changing the selected hull, respectively.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

It's definitely an oversight - I thought I already added that back. Also nice pun :D 

Best regards
Veetor

**Comment by molbal** [comment]
This should be fixed now

**Comment by Salvoxia** [comment]
Any chance of pre-selected the last used fitting for the selected hull as well? Now and then I forget to select the fitting and submit a run with "Unknown Fit", even if I didn't mean to...

**Comment by molbal** [comment]
I want that too, but it comes with an dynamic endpoint and it's a bit of extra effort to pass another flag to the API endpoint listing the fits. However I've been using it for a while and I also think that this will be inevitable
