### ISSUE TITLE
Different detailed table ISK total and the summary total ISK show a different value

### ISSUE THREAD

**Issue by molbal** [molbal/abyss-tracker#25]
The total run loot isk and the exact loot isk are very different in this run (39m vs 22m), the correct total isk should be 22m

https://abyss.eve-nt.uk/run/19096

**Comment by molbal** [comment]
It could be reproduced again::

https://abyss.eve-nt.uk/run/19372

This did not use the after/before loot comparsion, just the regular one. Same as the original one

**Comment by Salvoxia** [comment]
Another one, but the other way round: Summary total ISK is lower than the detailed one.
https://abyss.eve-nt.uk/run/22198
Even if the total ISK is already the profit, it's off by 200k.

**Comment by molbal** [comment]
Good catch! Next patch (1.5.2) will have a fully reworked loot calculation backend which will be shared with the fit parser too. It drops Evepraisal as a source and adds Eve Workbench appraisal and Fizzwork Marketdata.

**Comment by molbal** [comment]
Published fix with 1.5.2.

**Comment by Salvoxia** [comment]
One question for better understanding: I noticed that the summary total ISK does match neither the total sell order value, nor the total buy order value from the detailed table, but seems to use the arithmetic mean of both values (which makes sense). Is that observation correct?

**Comment by molbal** [comment]
Yes, you are correct. It is the mean of the cheapest high order and the most expensive buy order, with all blueprints counted as 0.
