### ISSUE TITLE
Arranging in My Runs

### ISSUE THREAD

**Issue by DemiOmbra** [molbal/abyss-tracker#26]
Hi,

When I go to "My runs" And want arrange on anything (value,date,...) the site automatically takes me to the "All runs" page instead of arranging it on " My runs".

Best regards,
Demi Ombra

**Comment by molbal** [comment]
Hi,

Fixed and published with https://github.com/molbal/abyss-tracker/commit/a967e5c6bf17eb4db4789d155ec5ac8a378fbfce

Thanks for telling me about it!

Best regards,
Veetor
