### ISSUE TITLE
Error when adding a run for T5 bonus room

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#27]
Hi,

I just found the T5 bonus room option, and tried adding a run when I rolled it.
I used the following loot and got the following error, which can be reproduced reliably: https://flareapp.io/share/q5YwyDPX
```
Crystalline Isogen-10	240	Abyssal Materials			84 m3	13.642.449,60 ISK
Gravid Gyrostabilizer Mutaplasmid	1	Mutaplasmids			1 m3	5.772.446,08 ISK
Light Compact Entropic Disintegrator Blueprint		Precursor Weapon Blueprint			0,01 m3	
Men's Triglavian Survival Suit (Bioadaptive)	1	Outer			0,10 m3	27.946.417,91 ISK
Triglavian Semiosis Data Vault (AFN)	1	Trinary Data Vaults			10 m3	
Zero-Point Condensate	419	Abyssal Materials			104,75 m3	39.827.504,49 ISK
```

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

I applied a temporary fix since in the long term I'm planning to switch to Eve Workbench's appraisal API from Evepraisal.

Exception suppressed with https://github.com/molbal/abyss-tracker/commit/9ba35faada984b579a4f19e019816a61409dc52e - and fix published.

Best regards,
Veetor

**Comment by Salvoxia** [comment]
Hmm, I'm intrigued that the Semiosis Data Vault seems to be the issue, while I'm sure that I've posted runs with it in the loot before, successfully (as have many others, according to the loot table).
Any idea what changed on Evepraisal's side..? When I pasted the loot manually at Evepraisal, there was no error (but the Data Vault was marked purple).

**Comment by molbal** [comment]
I am not sure either.. it is becoming unreliable lately, and it sometimes misparses input but I cannot consistently reproduce it
