### ISSUE TITLE
Fit picker: "Last viewed fit" not updating correctly

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#29]
Hi,

the "Last viewed fit" in the Fit Picker does not seem to update at all. No matter what fit I view, and then try to add a run, it still displays some other fit as "Last viewed fit".
Moreover, it displays the last viewed fit even if it is for a different hull than I have selected. And then selecting that last viewed fit, I can submit the run with a fitting for a different hull than the one that is selected.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

The last selected one is a by design choice, but I see how it looks more like a bug. This will be handled together with making the new run page automatically select the fit too.

Best regards,
Veetor

**Comment by molbal** [comment]
Commit https://github.com/molbal/abyss-tracker/commit/2c11c501116843ea2e2ad8af2882e2a6754d496e fixes this. Will be published with the rest of 1.5.2 once we have a few more fixes ready.

**Comment by molbal** [comment]
Published fix with 1.5.2.
