### ISSUE TITLE
Fit Picker not respecting fit privacy setting

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#30]
Hi,

the Fit Picker does not seem to respect fit privacy settings. Under the section "Public and anonym fits", it also displays private fits. I can select and submit a run for such a private fit.

Example:
![image](https://user-images.githubusercontent.com/6501566/82695755-00aa9d00-9c66-11ea-9d17-e8e0b440f9eb.png)
Fit [127](https://abyss.eve-nt.uk/fit/127) is a private fit, [128](https://abyss.eve-nt.uk/fit/128) is the public version of it.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

This was an ugly one even if the fit view page threw a 403 correctly. Fixed and published without waiting for the next release in https://github.com/molbal/abyss-tracker/commit/8786acca7fb0f5b0d8b8d9885bc1aeba0af9dc71 

Best regards,
Veetor

**Comment by Salvoxia** [comment]
Hi,

follow-up question: Is it intentional that runs that are linked with a private fit show the fit name and link (even though the fit cannot be viewed)?

Example: https://abyss.eve-nt.uk/run/21329

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hey,

Nah it was not intentional. I'm reopening the ticket, but reducing its severity a bit

Best regards,
Veetor

**Comment by molbal** [comment]
Commit https://github.com/molbal/abyss-tracker/commit/2c11c501116843ea2e2ad8af2882e2a6754d496e fixes this. Will be published with the rest of 1.5.2 once we have a few more fixes ready.

**Comment by molbal** [comment]
Published fix with 1.5.2.
