### ISSUE TITLE
Plugin for SeAT

### ISSUE THREAD

**Issue by xenon007** [molbal/abyss-tracker#32]
Hi! You maked cool app.

Is it possible by you make a plugin for SeAT for EVE Online 
https://github.com/eveseat/

**Comment by molbal** [comment]
Hi!

Thank you!

I am sorry I do not know SeAT yet. What kind of information/API would you need? I'm willing to make endpoints for you

**Comment by xenon007** [comment]
I liked the functionality and the idea. I would like the tracker to be available in a sieve with its design, authorization, etc. But I don’t want to rewrite your project. As for the endpoint, I find it difficult to answer

**Comment by molbal** [comment]
I'm sorry I have not used SeAT yet so I do not know what is a sieve there?

**Comment by xenon007** [comment]
SeAT its a small corporation/ally mgr tool. you can try it deploy via docker =)
