### ISSUE TITLE
Cannot unselect fit when adding new run

### ISSUE THREAD

**Issue by CrenshawCoding** [molbal/abyss-tracker#42]
**Describe the bug**
Cannot unselect fit when adding new run. There is no "noselect" option.

I did runs with a Sacrilege, now I am flying Vagabond with no fit uploaded, and I cannot unselect a fitting.

**To Reproduce**
1. add a run with a fit
2. add a run with a different ship
3. try to unselect the fit of the previous ship

**Expected behavior**
Provide an option to add a run with no fitting uploaded.

**Screenshots**
![Screenshot](https://i.imgur.com/7VfS0vy.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - dunno

**Smartphone (please complete the following information):**
 - no

**Comment by CrenshawCoding** [comment]
A minor addition: You are able to save runs with fittings, that do not belong to the ship. In my case I added runs with the vagabond, with a sacrilege fitting.

**Comment by molbal** [comment]
Thanks for the report - I was able to reproduce both issues. Next patch will contain a fix

**Comment by molbal** [comment]
Commit https://github.com/molbal/abyss-tracker/commit/a7bc8a4c7cad7b33236b2692d55f88d6cdcf3dd4fixes this - it will be published with the rest of patch 1.5.4

**Comment by CrenshawCoding** [comment]
Keep up the good work my man
