### ISSUE TITLE
Http Error 500 on new run with emtpy rows

### ISSUE THREAD

**Issue by stiez** [molbal/abyss-tracker#43]
If I try to add a new run I get an Server Error 500. Once I remove the emty rows the run can be submitted normally, so I don't believe the other information are of relevance but you never know.

T5 Dark with the Sacri fitting "Into the Abyss PIMP" and manual entry of 13 minutes. The run was set to private.

The formatting is broken in the post so I added a pastebin:

[Link](https://pastebin.com/9uheRPmK)

Before:

> Caldari Navy Inferno Heavy Assault Missile	4.860	Heavy Assault Missile			72,90 m3	6.429.780,00 ISK
> Caldari Navy Nova Heavy Assault Missile	4.847	Heavy Assault Missile			72,71 m3	7.042.981,82 ISK
> Chaotic Dark Filament	2	Abyssal Filaments			0,20 m3	32.078.231,14 ISK
> 
> 
> 
> Inferno Rage Heavy Assault Missile	5.040	Advanced Heavy Assault Missile			75,60 m3	706.003,20 ISK
> Mobile Tractor Unit		Mobile Tractor Unit			100 m3	7.197.856,60 ISK
> Nanite Repair Paste	196	Nanite Repair Paste			1,96 m3	5.638.043,88 ISK
> Nova Rage Heavy Assault Missile	4.658	Advanced Heavy Assault Missile			69,87 m3	878.359,06 ISK
> 
> 
> 

After:

> Caldari Navy Inferno Heavy Assault Missile	4.860	Heavy Assault Missile			72,90 m3	6.429.780,00 ISK
> Caldari Navy Nova Heavy Assault Missile	4.847	Heavy Assault Missile			72,71 m3	7.042.981,82 ISK
> Chaotic Dark Filament	2	Abyssal Filaments			0,20 m3	32.078.231,14 ISK
> Crystalline Isogen-10	134	Abyssal Materials			46,90 m3	6.640.178,38 ISK
> Decayed 1MN Afterburner Mutaplasmid	1	Mutaplasmids			1 m3	82.440,64 ISK
> Gravid Ballistic Control System Mutaplasmid	1	Mutaplasmids			1 m3	10.137.339,20 ISK
> Inferno Rage Heavy Assault Missile	5.040	Advanced Heavy Assault Missile			75,60 m3	706.003,20 ISK
> Mobile Tractor Unit		Mobile Tractor Unit			100 m3	7.197.856,60 ISK
> Nanite Repair Paste	196	Nanite Repair Paste			1,96 m3	5.638.043,88 ISK
> Nova Rage Heavy Assault Missile	4.658	Advanced Heavy Assault Missile			69,87 m3	878.359,06 ISK
> Tetryon Exotic Plasma XL Blueprint		Exotic Plasma Charge Blueprint			0,01 m3	
> Triglavian Survey Database	614	Triglavian Data			61,40 m3	61.400.000,00 ISK
> Zero-Point Condensate	17	Abyssal Materials			4,25 m3	1.445.415,31 ISK

Result: 500 | Server Error with Debugger Information "Error: Incorrect contents fetched, please reload."

**Comment by molbal** [comment]
Thanks for the report. Commit https://github.com/molbal/abyss-tracker/commit/96a7d0ac06ca181da7eb395af25da6c061ba50ad fixes it. Since the workaround is simple (remove empty lines) this fix will wait for the next patch (1.5.4) to  be released.

**Comment by molbal** [comment]
Also, this is a wonderfully detailed report and it was very easy to reproduce/fix, thank you :)

**Comment by stiez** [comment]
Thanks a lot :)
