### ISSUE TITLE
Bellicose listed under Frigates

### ISSUE THREAD

**Issue by richarddewit** [molbal/abyss-tracker#48]
**Describe the bug**
Not groundbreaking, but Bellicose, being a Cruiser (and having it stated as so) is listed under Frigates in **Most used ships**

**To Reproduce**
1. Go to **[Most used ships](https://abyss.eve-nt.uk/ships)**

**Expected behavior**
Bellicose should be listed under Cruisers

**Screenshots**
![image](https://user-images.githubusercontent.com/7933750/87121304-c7180a80-c282-11ea-96ce-2896a3ceb5b7.png)

**Comment by molbal** [comment]
That's right! Fixed

Thanks for the well formed report
