### ISSUE TITLE
2 Feature request: Median and Add run -> next run

### ISSUE THREAD

**Issue by KurodaAkira** [molbal/abyss-tracker#50]
So far I am missing two features for the site to have everything I'd like to use.

1. Median calculation. Taking the average loot amount is good and all but it skews what you consider an average run. For example for T4 runs, most of my runs are between 28-34mil in loot while my average is closer to 40-45mil due to getting around 20mil for a "bad" run but 90mil+ for a "good" run. Hence I'd like to be able to see a median calculation for the tracker.

2. Add run -> Next. So far I always have to manually start a new run after finishing one. Getting a button which would save the entered data but instead of sending you to the page of the run you just had, sends you right back to add a new run.

**Comment by molbal** [comment]
Next option added.
Median is already used for the 'commentary' up top (instead of avg.) and displayed in graph in the second tab. Please comment if its good enough or detail the median request a bit :)

**Comment by KurodaAkira** [comment]
Seeing the median at the graph tab is enough. Thank you.
