### ISSUE TITLE
Vedmak Blueprint not added as run loot

### ISSUE THREAD

**Issue by antoniohf** [molbal/abyss-tracker#51]
Hello,

When adding the run, the blueprint was ignored and does not show in the loot.

**To Reproduce**

Add run with the following loot:

Vedmak Blueprint	0
Calm Gamma Filament	2
Triglavian Survey Database	32
Crystalline Isogen-10	8
Precursor Battleship	1

After clicking save, you are redirected to the loot summary and Vedmak Blueprint is ignored and not added.

**Comment by molbal** [comment]
Hello,

The number next to the Vedmak Blueprint is 0, so the site thinks you didn't loot any, that's why it's ignored.

Does this answer your question?

**Comment by 36864** [comment]
This happens if you copy/paste your loot in icon mode instead of list mode. Always be sure to change your inventory display setting to list or detail view before copying.

**Comment by molbal** [comment]
Huh in this case I shall add a notification

**Comment by antoniohf** [comment]
@36864 copying with display set to list it works. thanks!

@molbal i realized that but since it had worked on previous occasions, i though it could be related to the item itself. Anyway, now i know why it had worked in the past - icon mode does not work.


Thanks both for the help.
