### ISSUE TITLE
Cargo of runs back to back

### ISSUE THREAD

**Issue by KurodaAkira** [molbal/abyss-tracker#52]
I do my runs usually only a minute or so apart from each other but I empty my cargo between runs. Unfortunately the new system automatically pastes the loot from the previous to the initial cargo of the next run. It would be great if this could be deactivated.

**Comment by molbal** [comment]
Hello,

Yes that is reasonable. I'll add a toggle in options for this!

Cheers,
Veetor

**Comment by KurodaAkira** [comment]
thank you :)

**Comment by molbal** [comment]
Toggle added in 1.5.5
