### ISSUE TITLE
My Fits List

### ISSUE THREAD

**Issue by KurodaAkira** [molbal/abyss-tracker#56]
I have been uploading a few of the fits I use for abyssals (and those I recommend to new players just starting out).
Unfortunately it is really ahrd to keep track of which fits I have already added to the tracker because I could not find a page which lists only the fits I added.
Is there an option like this I have simply been missing?
If not, could you add one?

**Comment by molbal** [comment]
Yeah, this is indeed missing, you are correct. I always forget adding it.

**Comment by molbal** [comment]
Implemented, scheduled for release with v1.6 (Next patch)
![Screenshot_2020-09-14 Fits Abyss Tracker DEV](https://user-images.githubusercontent.com/5754480/93030694-387a8d80-f625-11ea-8b8d-625713e84763.png)
![Screenshot_2020-09-14 Fits Abyss Tracker DEV(1)](https://user-images.githubusercontent.com/5754480/93030695-39abba80-f625-11ea-89e6-2b120dad159c.png)
