### ISSUE TITLE
Alt Character

### ISSUE THREAD

**Issue by KurodaAkira** [molbal/abyss-tracker#57]
A probably somewhat odd request:
I run abyssals on more than one character (due to skills. I can't very well show new players how to run abyssals with near maxed or maxed skills for the ships I recommend them). I also like to challenge myself at times by running only on an alpha.
Would it be possible to mark a character as an alt and add the runs to the list of runs I see on my main at the tracker?

**Comment by molbal** [comment]
It's definitely not impossible, or difficult, but I hope its OK if I ship the next patch without it since its such a unique request.

**Comment by molbal** [comment]
In progress for 1.10, ETA ~4-8 days

**Comment by molbal** [comment]
![Screenshot_2021-04-17 My stats (Veetor Nara) Abyss Tracker](https://user-images.githubusercontent.com/5754480/115111689-c33bb600-9f81-11eb-8047-f77dd1ddab4d.png)
