### ISSUE TITLE
Shipyard Room Exit

### ISSUE THREAD

**Issue by KurodaAkira** [molbal/abyss-tracker#58]
T5s can have a special run with only one room and a lot of leshaks in it. There will be an already open origin conduit there.
Sometimes I have to bail these without getting any loot but the run still consumes a filament (and I sometimes have to abandon drones). But the tracker does not allow for an option "didn't loot anything due to shipyard room" or for the loot list to be empty (even though I sometimes have to add drones in the "before cargo" to mark them as lost)

**Comment by molbal** [comment]
You can already scroll down and select the special room in the tier list:
![kép](https://user-images.githubusercontent.com/5754480/91607244-ddce0a00-e973-11ea-9665-ff7703b5011e.png)

..

Which I was taking a screenshot of and discovered that its buggy and does not save it properly. However, if it worked correctly, it would show up like this:
![kép](https://user-images.githubusercontent.com/5754480/91607497-4917dc00-e974-11ea-89ec-75a6ac1a67a6.png)

I'll fix it then you can try it out :) The T5 bonus room behaves the same as a regular T5 room in the Abyss Tracker, except it displays that message.

**Comment by KurodaAkira** [comment]
I did not notice there's a scroll bar. interesting.

**Comment by molbal** [comment]
Note: the upcoming T6 difficulty will not have the special room

**Comment by molbal** [comment]
Fixed the bug + made sure to show all entries when it fits on the screen, without scrollbar
