### ISSUE TITLE
Suggestion: Option to make private runs public 

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#6]
Hi,

this is more of a question/suggestion combination. If what I'm asking is already possible, please just close it.

If I understand things correctly, the public profile only shows runs, if they are submitted not anonymously and the profile setting allows it.
If I later change my mind and want to make my anonymous runs public, can I do that already?
If yes, how?
If not, I suggest to add that possibility.
(Yay, four subsequent sentences starting with"if".)

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi Salvoxia,

Good idea, implemented it, now its online :)

(4 sentes what combo is that?! :D )

Best regards,
Veetor
