### ISSUE TITLE
Error deleting a run

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#7]
I tried to delete one of my runs, and the following exception was thrown:

```
lluminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`abyss`.`detailed_loot`, CONSTRAINT `dl_run_id_foreign` FOREIGN KEY (`RUN_ID`) REFERENCES `runs` (`ID`)) (SQL: delete from `runs` where `ID` = ? and `CHAR_ID` = ?)
```

If you need the run ID, I can sent it to you ingame (yes, I'm paranoid ;) ).

Best Regards,
Salvoxia

**Comment by molbal** [comment]
I finally added foreign keys to link the tables together, probably a side effect of that. In this commit: https://github.com/molbal/abyss-tracker/commit/54b64d1780d92089439d52dd7252d0dca72934fe I tried a fix. It worked with 2 deletions for me now, so please try again!

I do not need you to send the ID of the run. 

Cheers,
Veetor

**Comment by Salvoxia** [comment]
Works now as expected, thank you!
