### ISSUE TITLE
Fit stats: tier 0 durations ignored

### ISSUE THREAD

**Issue by molbal** [molbal/abyss-tracker#71]
**Describe the bug**
All tier0 runs are calculated with 20minutes runtime, regardless of the actual result for example https://abyss.eve-nt.uk/fit/1046

**Comment by zmsMarc** [comment]
Similarly this was an average of 20min while only running T1 sites.
After I ran a single T0 the average runtime is now set to the time it took for the T0 site.
https://abyss.eve-nt.uk/fit/988

**Comment by molbal** [comment]
Fixed with an 1.9, published in 1.10 (But its already online, because it was easy to patch)
