### ISSUE TITLE
can't delete fit

### ISSUE THREAD

**Issue by freed-git** [molbal/abyss-tracker#80]
**Describe the bug**
can't delete a fit

**To Reproduce**
delete a fit

**Expected behavior**
fit should be deleted

**Screenshots**
https://user-images.githubusercontent.com/21298544/107298830-1f470300-6a44-11eb-8522-91a7412b0f70.png

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by molbal** [comment]
Hey,

Thanks for the report. It's a known issue, fix is coming next patch (unknown ETA for the time being)

BR,
Veetor
