### ISSUE TITLE
Rodiva fit won't upload.

### ISSUE THREAD

**Issue by eelowe0** [molbal/abyss-tracker#84]
I have a habit of trying things which shouldn't work in eve. 

While doing so i tested a rodiva fit both on sisi and tq

It's terrible but it works

Your site won't allow a rodiva fit tobe uploaded.

It may have once been the case that the rodiva couldn't enter the abyss but it can now

Interested to see if anyone else has the same kind of silly ideas i do

**To Reproduce**
1. Try to upload a rodiva fit
2. It won't

**Expected behavior**
The fit to upload

**Screenshots**
(https://i.imgur.com/y9MbQSp.png)

**Desktop (please complete the following information):**
 - OS: win 10  [e.g. iOS]
 - Browser chrome [e.g. chrome, safari]
 - Version 89.0.4389.90 (official build) (64biit)[e.g. 22]

**Comment by molbal** [comment]
Hi,

It should upload now :)

Cheers,
Veetor

**Comment by eelowe0** [comment]
cheers - works now :)
