### ISSUE TITLE
Error 500 when submitting a run on https://abyss.eve-nt.uk

### ISSUE THREAD

**Issue by lk77** [molbal/abyss-tracker#85]
Hello,

**Describe the bug**
Error 500 when submitting runs on https://abyss.eve-nt.uk/new

**To Reproduce**
1 : go to https://abyss.eve-nt.uk/new
2 : submit this run :

exotic T1 / just biocache
survived / fit #1918

timing : 10:30

loot :
```
Triglavian Survey Database	39	Triglavian Data			0,39 m3	3 900 000,00 ISK
Zero-Point Condensate	16	Abyssal Materials			3,20 m3	956 490,56 ISK
Event 22 Proving Filament	7	Abyssal Proving Filaments			0,70 m3	
Raging Gamma Filament	1	Abyssal Filaments			0,10 m3	8 188 043,18 ISK
Fierce Exotic Filament	1	Abyssal Filaments			0,10 m3	4 827 682,66 ISK
Decayed Warp Scrambler Mutaplasmid	1	Mutaplasmids			1 m3	30 734,40 ISK
Calm Firestorm Filament	1	Abyssal Filaments			0,10 m3	5 347,98 ISK
Calm Dark Filament	1	Abyssal Filaments			0,10 m3	6 697,88 ISK
```

**Expected behavior**
The run is created and complete

**Screenshots**

![Capture](https://user-images.githubusercontent.com/9606882/112730784-b2c08e80-8f33-11eb-9a81-0b65cf29e551.PNG)

**Desktop :**
 - OS: windows
 - Browser Chrome
 - Version 89

**Additional context**
run created but incomplete : https://abyss.eve-nt.uk/run/105690

it's not the first time, it happens a lot.

it seems that :

```
Event 22 Proving Filament	7	Abyssal Proving Filaments			0,70 m3	
```

is causing the issue, perhaps because it's not priced.

i've tried again without it and it worked : https://abyss.eve-nt.uk/run/105697

thanks.

**Comment by molbal** [comment]
Hi,

Sorry for the issue and thanks for the detailed report. I'll talk to the EVE Workbench dev Lionear to add this item so it works on the tracker, too.

o7

**Comment by Lionear** [comment]
@molbal @lk77 thanks for this report. We are investigating why EVE Workbench is missing this information. When we have it resolved I will post it back into this ticket so @molbal can close it :)

**Comment by lk77** [comment]
thanks !

**Comment by Lionear** [comment]
@lk77 @molbal the item **Event 22 Proving Filament** should now be known to our database. Sorry for the inconvenience! We will add some extra monitoring on this in the 1.10 release of EVE Workbench.

**Comment by molbal** [comment]
Thank you
