### ISSUE TITLE
Adding a Video requires new fit

### ISSUE THREAD

**Issue by glennowakowski** [molbal/abyss-tracker#88]
Description:
To add a video to the fit required "edit fit" and even if the EXACT fit is copied in order to progress through the wizard - then the addition of the tutorial video creates a new fit with new fit ID.  This means all of the data is no longer easily presented for the fit (instead it must be viewed via history).

**To Reproduce**
1. Go to '...SETTINGS'
2. Click on '....EDIT FIT'
3. Paste SAME FIT exactly (export tab)
4. Add video link

**Expected behavior**
A new fit ID not to be created, else another way to add a video tutorial without having to move through the edit fit wizard.

**Comment by molbal** [comment]
Good point! I'll _eventually_ get there

**Comment by glennowakowski** [comment]
I'll "bounty" this - as I think its a serious QoS issue.  $10 for the enhancement pledged!
Q:Why so serious?
A: New characters look at fits in Ascending order; thus fits with high numbers of "runs" are what they see.  If I cannot add a video to it, then effectively more players are running a "classic fit" without video instruction, where they could have had it!  P.S. The players I'm sending here are Newbro's/Eve-Unistas ... See the connection? :)

Paying forward in good faith, and thank you for what you do!

**Comment by molbal** [comment]
Hey,

Implementation done. I'm doing a few more bugfixes, then it will be online.

Link opening the modal:
![kép](https://user-images.githubusercontent.com/5754480/115156037-beaaf680-a082-11eb-8035-aceff963fc00.png)

Modal window:
![kép](https://user-images.githubusercontent.com/5754480/115156071-e0a47900-a082-11eb-8705-1ea249cd260f.png)

Saved message:
![kép](https://user-images.githubusercontent.com/5754480/115156102-0c276380-a083-11eb-906d-2d383fa7e248.png)

**Comment by glennowakowski** [comment]
This doesn't seem to allow you to "add/edit" it only appears to allow "edit" ... I.E. a fit without a video cannot add one.
Thanks for the addition/update.  Awesome!

**Comment by glennowakowski** [comment]
So stinking excited!!!

**Comment by molbal** [comment]
It's online now!

**Comment by glennowakowski** [comment]
I'm having trouble with this on all of my fits - - did the hotfix kill it?  When I go to click it on Opera it shows "javascript:void(0)" in my status bar, with no effect on click... 

![eve-abyssal-tracker-javascripvoid0](https://user-images.githubusercontent.com/20629102/115595391-7b2bd480-a29c-11eb-80a3-c00ae66c7cc4.png)

**Comment by molbal** [comment]
I forced a .js file refresh on client side - it should open for your now correctly
