### ISSUE TITLE
Automatically open Before Cargo/After Cargo panels

### ISSUE THREAD

**Issue by CrenshawCoding** [molbal/abyss-tracker#9]
I always use the Before Cargo/After Cargo panels, and I think it'd be awesome if there was an option to automatically have them open after I open the "add run" page.

**Comment by molbal** [comment]
Hello,

Sure, good idea. I'll make it the same as the other pre-fills: If in the previous run you had before-after cargo, then it will automatically switch to that view.

I think I can get to it next week

Cheers
Veetor

**Comment by molbal** [comment]
Hello,

Development is complete and now online.
(From version 1.4.2: https://github.com/molbal/abyss-tracker/releases/tag/1.4.2)

Cheers,
Veetor
