### ISSUE TITLE
Ammo shows up as both lost and looted

### ISSUE THREAD

**Issue by Sonreir66** [molbal/abyss-tracker#91]
**Describe the bug**
When submitting a run where you have before cargo and after cargo, your ammo shows in both the loot and the used sections.

**To Reproduce**
1.) Begin the "add a run" workflow
2.) Paste the contents of your cargohold into the before textfield
3.) Complete the run, using some of your ammo
4.) Paste the final contents of your cargohold into the after textfield

**Expected behavior**
Consumed ammo is shown in the used section and not in the looted section. If using crystals and no crystals were consumed, it should not appear in either section.

**Screenshots**
https://abyss.eve-nt.uk/run/113582

**Desktop (please complete the following information):**
Windows 10 - Chrome - Updated to latest version

**Comment by molbal** [comment]
A hotfix is now deployed - I'm monitoring it.

**Comment by molbal** [comment]
Requested function at the external service: https://github.com/E-351/janice/issues/14

**Comment by molbal** [comment]
Hey @Sonreir66,

I think the fix worked - can you confirm it, and close ticket?

**Comment by Sonreir66** [comment]
Fix worked.

**Comment by molbal** [comment]
Sweet thanks for feedback
