### ISSUE TITLE
Stacking & Duplicating Items

### ISSUE THREAD

**Issue by glennowakowski** [molbal/abyss-tracker#92]
**Describe the bug**
The total inventory is copying - the server is stacking it as it should - but then it duplicates the STACKED value as the individual items are listed.

**To Reproduce**
1. Go to '...'Copy Before cargo
2. Click on '....'Post After cargo
3. Scroll down to '....'DO NOT STACK your cargo before pasting
4. See a multiplicative increase in your loot

**Expected behavior**
should stack and remove the extra line items

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - LVL 2 (core: 73.0.3856.400)

**Additional context**
Will attempt to recreate more, but it has happened twice, and the issue seems severe enough to me that I submitted it quickly for disaster response (destroyed data) rather than worry about how accurate I am in the diagnosis of the "why" its happening.... Loot is being duplicated is the important part.

**Comment by molbal** [comment]
A hotfix is now deployed - I'm monitoring it.

**Comment by molbal** [comment]
I think its working fine now - closing the ticket.
